FROM node:14-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install -g json-server

COPY ./data /data

EXPOSE 4000

CMD ["json-server", "--watch", "/data/db.json", "--port", "4000", "--host", "0.0.0.0"]
