version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
    - json-server
  json-server:
    build:
      context: .
      dockerfile: Dockerfile.jsonserver
    ports:
      - 4000:4000
    volumes:
      - ./data:/data
